### PR TITLE
updated image link to point to connect-app static resources

### PR DESCRIPTION
**Pull request by akumar1503**
For [this](https://github.com/appirio-tech/connect-app/issues/2560) issue on connect app.

updated image link to point to connect-app static resorces in email templates.

### CODE REVIEW

**Comment by maxceem** [comment]
@vikasrohit this PR looks good to me. 

I think it can be merged. 

To apply changes we should do 2 things:
1. Deploy `cf17` which contains this [PR](https://github.com/appirio-tech/connect-app/pull/3026) which implement serving static files inside Connec App.
2. Update all the templates from this repository inside the Sendgrid.

**Comment by vikasrohit** [comment]
Thanks @maxceem. We will merge the cf17 as per our schedule i.e. after closing the challenge. What exactly we need to change in templates? We only have one template and you can do that changes [here](https://github.com/topcoder-platform/tc-notifications/tree/dev/emails/src/partials).

**Comment by maxceem** [comment]
@vikasrohit yes, the changes are already done in this PR we are commented to. You can have a look on the changed files https://github.com/topcoder-platform/tc-notifications/pull/116/files

**Comment by vikasrohit** [comment]
Thanks for pointer., I thought I am commenting on connect-app issue 😬. Will merge this PR when we merge the `cf17` in connect-app.

**Pull request merged**
