### PR TITLE
[Hotfix] [Prod] fix duplicates in emails

### PR DESCRIPTION
**Pull request by maxceem**
Fix for the issue which is tracked in Connect App https://github.com/appirio-tech/connect-app/issues/3216

Additionally, make a fix for a potential issue. See [commit message](https://github.com/topcoder-platform/tc-notifications/commit/9498198e468d00fab0aa2892a605d7f8103d29b4) for details.

### CODE REVIEW

**Comment by vikasrohit** [comment]
Just to confirm @maxceem we are not merging this hotfix to master, right?

**Comment by maxceem** [comment]
> Just to confirm @maxceem we are not merging this hotfix to master, right?

I was thinking that we would like to merge it to master as a hotfix. Looks like I've accidentally created it agains the `dev`.

**Comment by vikasrohit** [comment]
Okay, if we have the front end changes for it in our next hotfix for 2.4.15.2, we can create hotfix against master for this repo as well. No issue with that as well.

**Comment by maxceem** [comment]
> Okay, if we have the front end changes for it in our next hotfix for 2.4.15.2, we can create hotfix against master for this repo as well. No issue with that as well.

This issue only requires changes in the `tc-notifications` repo in this PR. No frontend changes are required. So it can be merged now as a hotfix, or it can be wait until the next release of the `tc-notificatons` repo if this issue is not urgent.

**Comment by vikasrohit** [comment]
Okay. Lets create hotfix for it against master as well. We would merge it with Connect 2.4.15.2

**Comment by maxceem** [comment]
Here is PR against `master` https://github.com/topcoder-platform/tc-notifications/pull/158

**Pull request merged**
